# Generated by Django 2.2.17 on 2023-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='size',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=2),
        ),
    ]
